// <auto-generated />
using System;
using API.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20211007161716_SeedInitialData")]
    partial class SeedInitialData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("API.Models.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("AccountId");

                    b.ToTable("tb_m_accounts");

                    b.HasData(
                        new
                        {
                            AccountId = 1,
                            AttemptCount = 0,
                            CreatedAt = new DateTime(2021, 10, 7, 23, 17, 15, 760, DateTimeKind.Local).AddTicks(4312),
                            Email = "admin@mail.com",
                            IsActive = true,
                            Name = "Super Administrator",
                            Password = "$2b$12$clsbfSGoIQc9iGyClefiT.wC8taXQBZ4JqlS46vAHACLTbF6/rBd6",
                            UpdatedAt = new DateTime(2021, 10, 7, 23, 17, 15, 760, DateTimeKind.Local).AddTicks(4687),
                            Username = "Admin"
                        });
                });

            modelBuilder.Entity("API.Models.AccountRole", b =>
                {
                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("AccountId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("tb_m_account_roles");

                    b.HasData(
                        new
                        {
                            AccountId = 1,
                            RoleId = "SP-ADM",
                            CreatedAt = new DateTime(2021, 10, 7, 23, 17, 15, 760, DateTimeKind.Local).AddTicks(6496),
                            UpdatedAt = new DateTime(2021, 10, 7, 23, 17, 15, 760, DateTimeKind.Local).AddTicks(6801)
                        },
                        new
                        {
                            AccountId = 1,
                            RoleId = "ADM",
                            CreatedAt = new DateTime(2021, 10, 7, 23, 17, 15, 760, DateTimeKind.Local).AddTicks(7090),
                            UpdatedAt = new DateTime(2021, 10, 7, 23, 17, 15, 760, DateTimeKind.Local).AddTicks(7095)
                        });
                });

            modelBuilder.Entity("API.Models.Candidate", b =>
                {
                    b.Property<int>("CandidateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CandidateId");

                    b.ToTable("tb_m_candidates");
                });

            modelBuilder.Entity("API.Models.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CompanyId");

                    b.ToTable("tb_m_companies");
                });

            modelBuilder.Entity("API.Models.DetailScheduleInterview", b =>
                {
                    b.Property<int>("DetailScheduleInterviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailCandidate")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("EmailCustomer")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ScheduleInterviewId")
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("TypeLocation")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("DetailScheduleInterviewId");

                    b.HasIndex("ScheduleInterviewId");

                    b.ToTable("tb_m_detail_schedule_interviews");
                });

            modelBuilder.Entity("API.Models.Onboard", b =>
                {
                    b.Property<int>("OnboardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("StatusId")
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("OnboardId");

                    b.HasIndex("CandidateId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("StatusId");

                    b.ToTable("tb_tr_onboards");
                });

            modelBuilder.Entity("API.Models.Role", b =>
                {
                    b.Property<string>("RoleId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RoleId");

                    b.ToTable("tb_m_roles");

                    b.HasData(
                        new
                        {
                            RoleId = "SP-ADM",
                            CreatedAt = new DateTime(2021, 10, 7, 23, 17, 15, 411, DateTimeKind.Local).AddTicks(1205),
                            Name = "Super Administrator",
                            UpdatedAt = new DateTime(2021, 10, 7, 23, 17, 15, 412, DateTimeKind.Local).AddTicks(357)
                        },
                        new
                        {
                            RoleId = "ADM",
                            CreatedAt = new DateTime(2021, 10, 7, 23, 17, 15, 412, DateTimeKind.Local).AddTicks(739),
                            Name = "Administrator",
                            UpdatedAt = new DateTime(2021, 10, 7, 23, 17, 15, 412, DateTimeKind.Local).AddTicks(744)
                        });
                });

            modelBuilder.Entity("API.Models.ScheduleInterview", b =>
                {
                    b.Property<string>("ScheduleInterviewId")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("EndInterview")
                        .HasColumnType("datetime2");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartInterview")
                        .HasColumnType("datetime2");

                    b.Property<string>("StatusId")
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ScheduleInterviewId");

                    b.HasIndex("CandidateId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("StatusId");

                    b.ToTable("tb_tr_schedule_interviews");
                });

            modelBuilder.Entity("API.Models.Status", b =>
                {
                    b.Property<string>("StatusId")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TypeStatusId")
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("StatusId");

                    b.HasIndex("TypeStatusId");

                    b.ToTable("tb_m_statuses");

                    b.HasData(
                        new
                        {
                            StatusId = "ITV-WT",
                            CreatedAt = new DateTime(2021, 10, 7, 23, 17, 15, 760, DateTimeKind.Local).AddTicks(9760),
                            Name = "Waiting",
                            UpdatedAt = new DateTime(2021, 10, 7, 23, 17, 15, 761, DateTimeKind.Local).AddTicks(50)
                        },
                        new
                        {
                            StatusId = "ITV-DN",
                            CreatedAt = new DateTime(2021, 10, 7, 23, 17, 15, 761, DateTimeKind.Local).AddTicks(424),
                            Name = "Done",
                            UpdatedAt = new DateTime(2021, 10, 7, 23, 17, 15, 761, DateTimeKind.Local).AddTicks(429)
                        },
                        new
                        {
                            StatusId = "ITV-CN",
                            CreatedAt = new DateTime(2021, 10, 7, 23, 17, 15, 761, DateTimeKind.Local).AddTicks(431),
                            Name = "Cancel",
                            UpdatedAt = new DateTime(2021, 10, 7, 23, 17, 15, 761, DateTimeKind.Local).AddTicks(432)
                        },
                        new
                        {
                            StatusId = "ONB-OG",
                            CreatedAt = new DateTime(2021, 10, 7, 23, 17, 15, 761, DateTimeKind.Local).AddTicks(434),
                            Name = "Cancel",
                            UpdatedAt = new DateTime(2021, 10, 7, 23, 17, 15, 761, DateTimeKind.Local).AddTicks(435)
                        },
                        new
                        {
                            StatusId = "ONB-DN",
                            CreatedAt = new DateTime(2021, 10, 7, 23, 17, 15, 761, DateTimeKind.Local).AddTicks(437),
                            Name = "Done",
                            UpdatedAt = new DateTime(2021, 10, 7, 23, 17, 15, 761, DateTimeKind.Local).AddTicks(438)
                        });
                });

            modelBuilder.Entity("API.Models.TypeStatus", b =>
                {
                    b.Property<string>("TypeStatusId")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("TypeStatusId");

                    b.ToTable("tb_m_type_statuses");

                    b.HasData(
                        new
                        {
                            TypeStatusId = "ITV",
                            CreatedAt = new DateTime(2021, 10, 7, 23, 17, 15, 760, DateTimeKind.Local).AddTicks(8145),
                            Name = "Schedule Interview",
                            UpdatedAt = new DateTime(2021, 10, 7, 23, 17, 15, 760, DateTimeKind.Local).AddTicks(8439)
                        },
                        new
                        {
                            TypeStatusId = "ONB",
                            CreatedAt = new DateTime(2021, 10, 7, 23, 17, 15, 760, DateTimeKind.Local).AddTicks(8722),
                            Name = "Onboard Candidate",
                            UpdatedAt = new DateTime(2021, 10, 7, 23, 17, 15, 760, DateTimeKind.Local).AddTicks(8726)
                        });
                });

            modelBuilder.Entity("API.Models.AccountRole", b =>
                {
                    b.HasOne("API.Models.Account", "Account")
                        .WithMany("AccountRoles")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Role", "Role")
                        .WithMany("AccountRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("API.Models.DetailScheduleInterview", b =>
                {
                    b.HasOne("API.Models.ScheduleInterview", "ScheduleInterview")
                        .WithMany("DetailScheduleInterviews")
                        .HasForeignKey("ScheduleInterviewId");

                    b.Navigation("ScheduleInterview");
                });

            modelBuilder.Entity("API.Models.Onboard", b =>
                {
                    b.HasOne("API.Models.Candidate", "Candidate")
                        .WithMany("Onboards")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Company", "Company")
                        .WithMany("Onboards")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Status", "Status")
                        .WithMany("Onboards")
                        .HasForeignKey("StatusId");

                    b.Navigation("Candidate");

                    b.Navigation("Company");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("API.Models.ScheduleInterview", b =>
                {
                    b.HasOne("API.Models.Candidate", "Candidate")
                        .WithMany("ScheduleInterviews")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Company", "Company")
                        .WithMany("ScheduleInterviews")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Status", "Status")
                        .WithMany("ScheduleInterviews")
                        .HasForeignKey("StatusId");

                    b.Navigation("Candidate");

                    b.Navigation("Company");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("API.Models.Status", b =>
                {
                    b.HasOne("API.Models.TypeStatus", "TypeStatus")
                        .WithMany("Status")
                        .HasForeignKey("TypeStatusId");

                    b.Navigation("TypeStatus");
                });

            modelBuilder.Entity("API.Models.Account", b =>
                {
                    b.Navigation("AccountRoles");
                });

            modelBuilder.Entity("API.Models.Candidate", b =>
                {
                    b.Navigation("Onboards");

                    b.Navigation("ScheduleInterviews");
                });

            modelBuilder.Entity("API.Models.Company", b =>
                {
                    b.Navigation("Onboards");

                    b.Navigation("ScheduleInterviews");
                });

            modelBuilder.Entity("API.Models.Role", b =>
                {
                    b.Navigation("AccountRoles");
                });

            modelBuilder.Entity("API.Models.ScheduleInterview", b =>
                {
                    b.Navigation("DetailScheduleInterviews");
                });

            modelBuilder.Entity("API.Models.Status", b =>
                {
                    b.Navigation("Onboards");

                    b.Navigation("ScheduleInterviews");
                });

            modelBuilder.Entity("API.Models.TypeStatus", b =>
                {
                    b.Navigation("Status");
                });
#pragma warning restore 612, 618
        }
    }
}
